def divide(a,b):
    return a/b
def addition(a,b):
    return a+b
def subtract(a,b):
    return a-b
def multiply(a,b):
    return a*b
def exponent(a,b):
    return a**b
def modulus(a,b):
    return a%b
def floor_div(a,b):
    return a//b
